#!/usr/bin/env python3
# gen-templates.py [templates-dir] [out-nix] [out-readme]
# defaults: ./templates  ./templates.nix  ./README.md

import json, subprocess, sys
from pathlib import Path

templates_dir = Path(sys.argv[1] if len(sys.argv) > 1 else "templates")
out_nix      = Path(sys.argv[2] if len(sys.argv) > 2 else "templates.nix")
out_readme   = Path(sys.argv[3] if len(sys.argv) > 3 else "README.md")

def get_description(path: Path) -> str:
    r = subprocess.run(
        ["nix", "flake", "metadata", "--json", f"path:{path}"],
        capture_output=True, text=True
    )
    if r.returncode != 0:
        return ""
    return json.loads(r.stdout).get("description", "")

def screenshots(path: Path) -> list[Path]:
    return [p for p in (path / "pics" / f"{n}.png" for n in (1, 2)) if p.exists()]

templates = sorted(
    (d for d in templates_dir.iterdir() if d.is_dir() and (d / "flake.nix").exists()),
    key=lambda d: d.name
)

if not templates:
    sys.exit(f"no templates found in {templates_dir}")

entries = [(t.name, get_description(t), screenshots(t)) for t in templates]

# ── templates.nix ─────────────────────────────────────────────────────────────

nix_attrs = "\n".join(
    f'  {name} = {{\n    path = ./templates/{name};\n    description = "{desc}";\n  }};'
    for name, desc, _ in entries
)
out_nix.write_text(
    f"# auto-generated by gen-templates.py — do not edit manually\n"
    f"{{\n{nix_attrs}\n}}\n"
)

# ── README.md ─────────────────────────────────────────────────────────────────

sections = []
for name, desc, pics in entries:
    lines = [f"### `{name}`", "", desc or "_no description_"]
    for p in pics:
        lines += ["", f"![{p.stem}]({p})"]
    sections.append("\n".join(lines))

table_rows = "\n".join(
    f"| [`{n}`](#{n}) | {d} |" for n, d, _ in entries
)

out_readme.write_text(f"""\
# nut-shells

NixOS flake templates for [nut](https://github.com/Francesco149/nut).

## usage

```sh
nix shell nixpkgs#git   # if you don't have git

mkdir my-config && cd my-config

# replace <template> with the template name. see below for a list
nix flake init -t github:Francesco149/nut-shells#<template>

git init
git add .

# .. or adapt to your current system wide config.
# just make sure to migrate everything over
cp /etc/nixos/configuration.nix ./hosts/nixos/
cp /etc/nixos/hardware-configuration.nix ./hosts/nixos/

sudo nixos-rebuild boot --flake .#nixos
passwd headpats # if the flake has a non-root user, set the password
reboot
```

if there's a non-root user, the default username is always `headpats` with no
password configured. remember to run `passwd headpats` or whatever you rename
the user to.

if for whatever reason the config doesn't boot, you can select the previous
generation in grub to roll back. NixOS perks!

refer to the [nut docs](https://github.com/Francesco149/nut) for next steps.

---

## templates

| name | description |
| ---- | ----------- |
{table_rows}

{"---".join(f"\n\n{s}\n\n" for s in sections).strip()}

---

## maintaining this repo

after adding, removing, or renaming a template, regenerate the nix attrset and
this README:

```sh
nix run nixpkgs#python3 -- ./gen-templates.py
```

then open `README.md` in vscode and save to auto-format.
""")

print(f"wrote {out_nix}")
print(f"wrote {out_readme}")