# auto-generated by gen-templates.py — do not edit manually
{
  default = {
    path = ./templates/default;
    description = "blank flake using nut";
  };
  hyprland = {
    path = ./templates/hyprland;
    description = "tiling desktop with frosted catpuccino aesthetics";
  };
}
